### ISSUE TITLE
Turning off mouselook causes the cursor to pan from side to side

### ISSUE THREAD

**Issue by Avonaeon** [JohnGlassmyer/UltimaHacks#1]
Hi,

Just tried this hack out on UW1. Used the website to hack the .exe and seems to work great, except when I turn off mouselook (After having it on) the cursor starts panning from side to side. It makes is hard to pick things up.
I can still influence the mouse by dragging the cursor to the upper right, but the cursor constantly wants to pan left and right at the center of the screen.

Let me know if you need more info!

**Comment by JohnGlassmyer** [comment]
Is it because the Tab key is stuck? I know that Alt+Tabbing in DOSBox causes the Tab key to get stuck until Tab is pressed again. And, in Underworld, the Tab key moves the cursor around the screen. I can't tell whether that is the issue you are having.

**Comment by Avonaeon** [comment]
That was exactly the issue! Thank you 👍
