### ISSUE TITLE
UW2 WASD movement is not working correctly

### ISSUE THREAD

**Issue by kherrmann3** [JohnGlassmyer/UltimaHacks#11]
First off, thrilled to see these patches. After playing System Shock with mouselook, and hearing it would be impossible to do with the UWs (ages ago), I had given up hope. But, felt inspired to google it last night and am thrilled it has been achieved. Thank you.

I am running from an extracted GOG image, and UW seems to work perfectly. The issue appears with UW2. Soon as I start the game, it starts moving me backwards and can't move forward. When I enable mouse look, it appears that I can move better depending on where I'm looking, but it feels so sporadic and quite the opposite of UW.

I used your hack applier to patch the executables.  

Thanks for any help, and thanks again for making this possible.

**Comment by JohnGlassmyer** [comment]
Are you using otherwise unmodified executables from GOG for both games? What keyboard region are you using? US English? What version of DOSBox? Is it a fresh install of DOSBox, or have you configured anything, like the key mapper?

**Comment by kherrmann3** [comment]
I had downloaded the complete UW1+2 nearly 10 years ago, from GOG, and was using that installer. I pulled the latest packages from GOG and that seems to have fixed it. 

Thank you!

**Comment by JohnGlassmyer** [comment]
Great! Let me know if you run into any other issues.

**Comment by kherrmann3** [comment]
Apologies, I may have spoken too soon. While, it seems to be better, there is still something going on. It's dosbox .74-2 that came with the UW1/2 package from GOG, freshly installed. Keyboard layout is "auto". 

Pretty much the only thing I did was run uinstall to configure audio, so roland/sbpro there. The window I configured to 1920x1080, but the issue happens even when I just launch dosbox and ignore the conf file. The binaries I'm using were patched from my old install, but the dates are the same, as I'm sure those haven't changed since '93. Mapper file is the default mapper that came with it.

So, the experience is almost like there is something pulling back on the character. When I set the cpu cycles to 50% it seems better, and I can move around better. But, that just seems to mask the issue. For instance, when it launches it is at 3000 cycles, if I crank those up to over 10000 it will start walk me backwards automatically. If I drop it down to ~4-5000, it seems to step me backwards once for every step forward.

**Comment by kherrmann3** [comment]
I commented out the mapper line on the dosbox conf, and it's smooth now.
#mapperfile=mapper-0.74-2.map

Will keep this open for a bit, just to confirm this has fixed it.

**Comment by kherrmann3** [comment]
Okay, not sure what is going on...I haven't changed anything since the last comment, but it's happening again, after a few restarts. I've tried different keyboards, just to verify that's not an issue. Really bizarre. Please, let me know if there are any details or configs you'd like to see...and I'll see about making a video.

**Comment by JohnGlassmyer** [comment]
Oh, now I remember something like this happening before.

There should be a DOSBox config option to disable joysticks; I'd try setting that, and seeing whether it fixes the issue.

Do you have any device like a gamepad, joystick, flight pedals, etc, connected to your computer when you start DOSBox / UW2? Any kind of controller other than the mouse and keyboard? Because a slightly uncalibrated joystick (or anything that DOSBox sees as a joystick) can pull your character steadily backwards.

**Comment by kherrmann3** [comment]
That was exactly what I was just pondering...the closest thing to that is my G13, but it happened after I unplugged it.

Then I remembered I hadn't rebooted the machine in awhile, just put it to sleep. So, I gave that a shot, and so far it's been consistently stable through 4 or 5 starts. I'll disable joysticks in dosbox, just to keep that out of the picture. It just seems so weird that it would happen with UW2, while UW was consistently working. 

Well, hopefully, that's all it was. Appreciate the support...it's amazing how much mouselook adds to these classic games.

**Comment by JohnGlassmyer** [comment]
I think joystick support was a new feature in UW2 that UW1 did not have. It ends up being more of a curse than a useful feature.

GOG should ship the game with joysticks turned off in the DOSBox config.

You might try experimenting by playing the game with the controller plugged in vs not plugged in, to build confidence in whether that's the issue.

**Comment by JohnGlassmyer** [comment]
I'm closing this again for now. Let me know if you run into any more problems.

**Comment by kherrmann3** [comment]
Thanks! So far so good.
