### ISSUE TITLE
Consider support for older builds of U7BG/U7SI?

### ISSUE THREAD

**Issue by leppaluo** [JohnGlassmyer/UltimaHacks#13]
First of all, thanks for this great patch collection! +1 for verifying that U7BG (v3.4) works well on real 486 hardware + AdLib + Roland.

I tried to patch my floppy release of U7BG version 3.0 on the **Hack Applier website** without success. Any possibility to add support for older versions of `U7.EXE` and `SI.EXE` (without FoV/SS) in the future?

Thanks!

**Comment by leppaluo** [comment]
> 
> 
> First of all, thanks for this great patch collection! +1 for verifying that U7BG (v3.4) works well on real 486 hardware + AdLib + Roland.
> 
> I tried to patch my floppy release of U7BG version 3.0 on the **Hack Applier website** without success. Any possibility to add support for older versions of `U7.EXE` and `SI.EXE` (without FoV/SS) in the future?
> 
> Thanks!

Just discovered that the original 3.0 release can be updated to 3.4 with an official patch, so the question is more to support plain U7BG and U7SI without the expansion packs.

**Comment by leppaluo** [comment]
Most likely this is an user-error as the non-FoV 3.4 version of U7BG can be hacked normally.

**Comment by JohnGlassmyer** [comment]
Great to hear that it works on some real hardware.
Please let me know if you run into further issues.
