### ISSUE TITLE
Add optional 24h-time format to U7.exe

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [JohnGlassmyer/UltimaHacks#14]
The original German U7.exed featured 24h time format. Is it possible to add this to the Ultimahacks as well? I can provide the original german file of course.
If not, is it possible, to add the original U7.exe (685.456 bytes) as patchable .exe?

**Comment by JohnGlassmyer** [comment]
in what context(s) is this relevant? off the top of my head i don't know whether you're referring to text printed by Usecode scripts (pocket watch, grandfather clock), the debug/cheat menu, something else?

**Comment by ungesundes-halbwissen** [comment]
Ouch, my bad. You're right. Just copied a hacked english u7.exe to a original German version of the game and still have 24h format. Sorry for the hassle.
