### ISSUE TITLE
UW2 patch breaks Serpent Statue subquest, among other things

### ISSUE THREAD

**Issue by bliznik** [JohnGlassmyer/UltimaHacks#15]
I've played through UW2 both with and without the patch included. There are some parts of the game that break with the patch.

(1) With the patch installed, I am unable to retrieve the Serpent Statue from the nameless goblin in the sewers. (https://groups.google.com/g/rec.games.computer.ultima.dragons/c/jylv7oeFJ9o, see 12.1.5) The entire subquest is broken. He never offers me the Serpent Statue, even after I learn tracking, and after I kill Patterson. Without the patch installed, I'm able to receive the Serpent Statue from the nameless goblin no problem.

(2) With the patch installed, Relk never moves back to his room after he tells me to meet me in his room. Instead, after I talk to Relk, he just hangs out in the same place, and attacks me the next time I talk to him. If I kill him immediately after he attacks me, everyone in the keep witnesses the fight, and then becomes hostile to me. The only workaround is to talk to Relk, lure him into an empty area (like his room), and then fight back. Without the patch installed, after Relk tells me to meet me in his room, he then disappears and reappears in his room. When I go to his room, he attacks me, and I'm able to fight back without any witnesses.

(3) With the patch installed, the people in the castle start shuffling locations. Geoffrey relocates from his room to the fountain area, Dupre relocates from his room to the dining hall, and Nanna relocates from the kitchen to the fountain area. Without the patch installed, all of the people in the castle mainly stay in the areas that they were originally found. 

Below are screenshots of the Serpent Statue quest that can only be completed without the patch installed.

![Screenshot_1](https://user-images.githubusercontent.com/26865598/120484574-1027f000-c368-11eb-9919-da86d36a32af.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/26865598/120484577-10c08680-c368-11eb-8e45-6b9c2fd11792.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/26865598/120484578-11591d00-c368-11eb-82af-c54c9b0598b5.jpg)

**Comment by JohnGlassmyer** [comment]
I suspect that these are coincidences; that these things happened to happen one way when you were playing with the patch installed and happened to happen the other way without it installed. Do you have a save file from the point exactly before each of these issues occurs, from which playing with the patch reliably (several times in a row) causes the issue to occur and from which playing without the patch reliably does not? I would need this sort of simple reproduceability in order to confirm these issues and in order to test any attempted fix.

**Comment by bliznik** [comment]
Hmm, you're absolutely right. I saved and loaded several savegames, and I couldn't reproduce these issues. It's possible that there was a configuration that was implemented with your patch installed, and then another configuration that was reset when I did a fresh install (which removed your patch) that allowed me to not trigger this bug.

Just to be safe, I'll restart a game with your patch installed, and nothing else configured (no music files or anything) and will see if I can reproduce these issues. You can close this issue. If I can reproduce this issue, I'll reopen this issue with more information and savegame files!

**Comment by JohnGlassmyer** [comment]
ok thanks!

**Comment by bliznik** [comment]
Confirmed. It wasn't your patch that broke these things. I suspect it was some other configuration things I did at the same time I installed your patch--it might have been upcycling the DOSBox conf. file. The mouselook patch works beautifully.
