### ISSUE TITLE
Ultima Underworld II patched features not working.

### ISSUE THREAD

**Issue by punkerteddy** [JohnGlassmyer/UltimaHacks#19]
I don't know if there is already a fix to this or i am missing something, but i have tried through DOSBox and GOG games, UW2.exe patched wont work.....  Dosbox Version 0.74-3 UW2.exe version vF1.99s i have zipped my installation folder of the game patched. please take a look  

[luw2.zip](https://github.com/JohnGlassmyer/UltimaHacks/files/7041404/luw2.zip)

**Comment by punkerteddy** [comment]
I found the issue had to installation folders for backup, the backup was mounted and wasnt patched....

**Comment by JohnGlassmyer** [comment]
not the first person to have that issue! i'm glad you got it sorted out.
