### ISSUE TITLE
Patcher site is down

### ISSUE THREAD

**Issue by hooby3dfx** [JohnGlassmyer/UltimaHacks#27]
Going to this URL results in a 404
https://johnglassmyer.github.io/UltimaHacks/

**Comment by JohnGlassmyer** [comment]
weird. thanks for letting me know. i see the error page, but i'm not sure why it's happening. did you just discover this recently?

**Comment by JohnGlassmyer** [comment]
it should work now. i ran into a problem hosting the patcher site from my private user repository, so i have switched to hosting it instead from the public project repository. note that the link / address is different than before.

**Comment by hooby3dfx** [comment]
thank you!!
