### ISSUE TITLE
Ctrl - Alt - M not working

### ISSUE THREAD

**Issue by captainkeel** [JohnGlassmyer/UltimaHacks#29]
This one is very strange: every Ctrl-Alt letter for runes works, except for M. Ctrl-Alt-Space and backspace also work correctly.

If it were a less common rune I'd even just suck it up but healing spells are pretty key unfortunately.

**Comment by JohnGlassmyer** [comment]
what type of keyboard were you using and which keyboard layout was your computer's operating system configured to use at the time? do you use any macro software that might reinterpret presses of keys?

**Comment by captainkeel** [comment]
It is a Corsair K-70 MK2 RGB Mechanical Gaming keyboard. Keyboard layout is QWERTY if I understand what you're asking. I do not use any macro software.

**Comment by DominusExult** [comment]
For example Nvidia's Shadow Play catches ctrl-alt-m

https://superuser.com/questions/1282799/what-is-preventing-ctrl-alt-m-from-reaching-intellij-on-windows-10#1293860

**Comment by captainkeel** [comment]
That's probably it, I will check it out when I get home tonight. Thank you.

**Comment by captainkeel** [comment]
That was it. Ended the Nvidia Shadowplay helper task and Ctrl-Alt-M begins to work. Thanks!
