### ISSUE TITLE
Inverted mouse look

### ISSUE THREAD

**Issue by sk2k** [JohnGlassmyer/UltimaHacks#3]
Would it be possible to add a key to invert the mouse y-axis? I play all games with inverted y-axis and it feels more than weird to play "normal". :)

Regards.

**Comment by JohnGlassmyer** [comment]
I've added a command to invert the X and Y mouse-look axes on Alt+Backquote (the same key as to toggle mouse-look, but with Alt held). It will cycle through 4 states (normal, invert Y, invert X, invert both).

Should be available through the Hack Applier website now.

Please let me know how it works for you.

**Comment by sk2k** [comment]
Hello.
Thanks! It works. Much better now. :D
