### ISSUE TITLE
UW and UW2 hacks stopped working

### ISSUE THREAD

**Issue by sk2k** [JohnGlassmyer/UltimaHacks#6]
After my HD crashed i downloaded, installed and patched (with the hack applier on your website) UW and UW2 again. Nothing works. No WASD, no mouselook, etc.
I wonder what is wrong. :(

EDIT: Please delete/close this. I'm just dumb. Everything works now. :)

**Comment by JohnGlassmyer** [comment]
I'm glad you figured it out : ) Do you mind saying what your mistake was?

**Comment by sk2k** [comment]
I made copies of the installation folders and used the copies without changing the folder paths in my bat files. When starting UW or UW2 everything pointed to the original unpatched installation. :D
